  CREATE TABLE "ICS_FLOW_LOCAL"."TRACK_RELATE" 
   (	"TABLE_NAME" VARCHAR2(64 BYTE), 
	"ANCESTOR_TABLE_NAME" VARCHAR2(64 BYTE), 
	"DEPTH" NUMBER(*,0), 
	"TABLE_PATH" VARCHAR2(4000 BYTE), 
	"JOIN_PATH" VARCHAR2(4000 BYTE), 
	"TABLE_ID" VARCHAR2(64 BYTE), 
	"ANCESTOR_TABLE_ID" VARCHAR2(64 BYTE), 
	"TABLE_ALIAS" VARCHAR2(64 BYTE)
   );
   