
-- UTLY_REL_TREE.Table.sql
-- MySQL
drop table if exists `UTLY_REL_TREE`;
CREATE TABLE `UTLY_REL_TREE` (
	`TABLE_NAME` VARCHAR(64) NULL DEFAULT NULL,
	`ANCESTOR_TABLE_NAME` VARCHAR(64) NULL DEFAULT NULL,
	`DEPTH` INT(11) NULL DEFAULT NULL,
	`TABLE_PATH` VARCHAR(4000) NULL DEFAULT NULL,
	`JOIN_PATH` VARCHAR(4000) NULL DEFAULT NULL,
	`TABLE_ID` VARCHAR(64) NULL DEFAULT NULL,
	`ANCESTOR_TABLE_ID` VARCHAR(64) NULL DEFAULT NULL,
	`TABLE_ALIAS` VARCHAR(64) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
