
-- UTLY_SQL_STATEMENTS.Table.sql
-- MySQL 
drop table if exists UTLY_SQL_STATEMENTS;
CREATE TABLE UTLY_SQL_STATEMENTS(
	STATEMENT_SEQ INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	STATEMENT_TEXT TEXT
);


