

/****** Object:  Table [dbo].[UTLY_SQL_STATEMENTS]    Script Date: 8/9/2017 4:27:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[UTLY_SQL_STATEMENTS](
	[STATEMENT_SEQ] [int] IDENTITY(1,1) NOT NULL,
	[STATEMENT_TEXT] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

