/****** Object:  View [dbo].[UTLY_VW_FK]    Script Date: 7/12/2017 9:05:08 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE view [dbo].[UTLY_VW_FK]
as
-- 2025-03-17 CRT: Add Schema for SqlServer
-- 2026-01-01 CRT: Restrict constraints scheama to be the same
SELECT 
	ccu.TABLE_SCHEMA as SCHEMA_NAME
    ,ccu.table_name AS TABLE_NAME
    ,ccu.constraint_name AS FK_NAME
    ,ccu.column_name AS COLUMN_NAME
	,kcu.TABLE_SCHEMA as FK_SCHEMA_NAME
    ,kcu.table_name AS FK_TABLE_NAME
    ,kcu.column_name AS FK_COLUMN_NAME
   
FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu
    INNER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
        ON ccu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME 
        and ccu.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA 
    INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu 
        ON kcu.CONSTRAINT_NAME = rc.UNIQUE_CONSTRAINT_NAME  
        and kcu.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA

GO


